# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9ae403952c70ec92759222f4845f119ca54993f47863374feec40a0bb248d0891c0205acd06f46e002d2c11ee62d89d923bc76b4e85f374c3d1f6b577cdac16

test:
  secret_key_base: b76bb25d7a2bf543bba809f2b284b527f16823c33238f0ab25b9f4821b4c13dc06c7bf3ce5f0740490d627e47ba9c6bc45fa6713c1904262a8dda77eff910014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
